### PR TITLE
Unit test for icd_explain on a vector, and consistency check vs. resu…

### PR DESCRIPTION
**Pull request by edlee123**
If I perform an icd_explain on the included test vector, the icd_explain function returns a vector of a different length from the input.  The behavior is different vs. if we Iapply icd_explain a single code at the time.   Is this behavior intended, or a regression?

### CODE REVIEW

**Comment by jackwasey** [comment]
Thanks for taking the trouble to make a unit test. This is in fact intended behaviour, since 414.01 is encompassed by 414. If you want to get an explanation for each and every code, then use the flag `condense = FALSE`. You did, however, find another little bug:
```
> icd_explain("362.5")
[1] "Of anterolateral wall"
```
This represents an RTF parsing error, as it should read: "Degeneration of macula and posterior pole of retina"

I can't do it right now, but I (or someone else?) will update your test to look for the parsing error, and see about a fix. Thanks again.

**Comment by edlee123** [comment]
Jack thank you for the tip, I see it now.  Glad I could be of some small service.  I can try take a stab at the parsing - would you have any pointers on where I might start?   I'm in the process of orienting myself with the package.   I don't have much medical background, but love R, and hope to learn more about ICD9s.

**Comment by jackwasey** [comment]
The RTF parsing is the part of the package I'm least happy with. The RTF is so messy. I did my best to keep the code tidy, but it is necessarily complicated, because there are subsections which apply to different subgroups in different parts of the document. E.g. a whole chapter might specify the meaning of the xxx.xX digit. The code is in `parse_rtf_lines` in `R/parse-rtf.R`.

Your eyes and expertise on this code would be much appreciated. As the RTF documents are no longer updated, since ICD-10 is now the new standard, I didn't spend any more effort than I had to to make it work. It may be best just to manually fix up results (possibly by RTF/ICD version year), than to try to make the logic better.

Would be interested to see if you can make this prettier, or better in any way, but it may just come down to defining some codes manually, as you can see I did at the end of the function.

**Comment by edlee123** [comment]
Thank you Jack for the tip that's v. helpful.  I brainstormed a couple ideas today.  The first one is along the lines of your last idea. If this is likely a one-off (?) maybe we can filter the remaining parse 'exceptions'.  One strategy I thought is create a 'similarity score' to help filter them out.  Mind you my understanding of ICD9 is still limited, but for example if there are some similarities between ICD9 and this ICD9-CM source [source](https://www.cms.gov/Medicare/Coding/ICD9ProviderDiagnosticCodes/codes.html),  we can then define a similarity threshold to filter for really dissimilar parses and hopefully not too large to eyeball.  That's the more ninja idea.  This week I'm little busy, but I'll explore it some more next week...

**Comment by edlee123** [comment]
Hi Jack,

Hope you are well. I just wanted to run something by you about the `condense = F` earlier. 

If I do this:

`testcodes <- c("362.5", "413.9", "414.01", "584.9", "357.2", "588.81", "414")`
`method1 <- icd_explain(testcodes, condense = F)`
`method2 <- as.vector(sapply(testcodes, FUN = function(x) icd_explain(x, condense = F)))`

At the moment method1 and method2 will be different because `icd_explain` orders major codes first (around line 109 of explain.R).  But we could return the explanations in the same order as the input vector when `condense = F`?    Are there any considerations if the behavior were this way?

Hoping maybe to tie in with [issue 84](https://github.com/jackwasey/icd/issues/84).  

<script src="https://gist.github.com/edlee123/f4cc357f3ff4e2338939dc3212234dfc.js"></script>

**Comment by jackwasey** [comment]
Thanks for picking that up. If I remember correctly, the list of results is
built up from nothing, so it would not be as simple as just sorting. Would
have to do something like creating a key value pair list, sorting the keys
and returning the values. A default of ordering by ICD code, instead
of 'major first' does make sense to me.

**Comment by edlee123** [comment]
Hi Jack,
I just want to summarise what I did regarding this pull request #92 .  I think it will resolve issue #95 and #96  as well. 

On the original issue #92, we found the odd case that we thought was a parsing error:
```
> icd_explain("362.5")
[1] "Of anterolateral wall"
```
 When I looked at the rtf document, it turns this is how the original Subcategory heading was written indeed, so I figured the rtf parser was mechanically correct.  To make it human comprehendible I added the major Category description as well.  I wrote this new function to provide more explanation:
```

> icd_explain_table("362.5")

  input shortcode three_digit majorcode ismajor              major_desc             long_desc            short_desc validicd9 validicd10

1 362.5      3625         362       362   FALSE Other retinal disorders Of anterolateral wall Of anterolateral wall      TRUE      FALSE
```

####  Differences between _icd_explain_table_ vs _icd_explain_: 

1) icd_explain_table is designed so it will output explanations in the same order as the input by default.  This addresses the ordering issue of  issue #96. 

I do also have a unit-test to show how to get to the same ordering as icd_explain with dplyr in: test-current-explaintable.R
 
2) icd_explain_table will provide info about condensing subcategories to the parent Category if you see see the right part of table below in row 3:
 
```
> testcodes <- c("362.5", "413.9", "414.01", "584.9", "357.2", "588.81", "414")
> icd_explain_table(testcodes, condense = T)

   input shortcode three_digit majorcode ismajor                                       major_desc
1  362.5      3625         362       362   FALSE                          Other retinal disorders
2  413.9      4139         413       413   FALSE                                  Angina pectoris
3    414       414         414       414    TRUE    Other forms of chronic ischemic heart disease
4  584.9      5849         584       584   FALSE                             Acute kidney failure
5  357.2      3572         357       357   FALSE                Inflammatory and toxic neuropathy
6 588.81     58881         ### 588       588   FALSE Disorders resulting from impaired renal function

                                        long_desc                     short_desc validicd9 validicd10 condensedcodes numcondensed
1                           Of anterolateral wall          Of anterolateral wall      TRUE      FALSE          362.5            
2           Other and unspecified angina pectoris        Angina pectoris NEC/NOS      TRUE      FALSE          413.9            1
3                  Ulcerative (chronic) proctitis Ulcerative (chronic) proctitis      TRUE      FALSE    414.01, 414            2
4               Acute kidney failure, unspecified       Acute kidney failure NOS      TRUE      FALSE          584.9            1
5                      Polyneuropathy in diabetes         Neuropathy in diabetes      TRUE      FALSE          357.2            1
6 Secondary hyperparathyroidism (of renal origin)       Sec hyperparathyrd-renal      TRUE      FALSE         588.81            1..
 ```
3.)   icd_explain_table will handle problem codes by returning rows with NA:

```
> icd_explain_table("bogus")
  input shortcode three_digit majorcode ismajor major_desc long_desc short_desc validicd9 validicd10
1 bogus      <NA>        <NA>      <NA>      NA       <NA>      <NA>       <NA>        NA         NA
```
 
4.)  icd_explain_table resolves issue #96 with codes that are both valid icd9 and icd10 codes.  The default behavior of ambiguous character codes is to show the icd10 descriptions, unless they are casted explicitly as.icd9.  I have generated the Rd help with devtools::document as well.  

Also if the input vector is of type character with mixed icd9 and icd19 it will output descriptions per the default behavior described.

_Examples_:
```
icd_explain_table("E11.9")
  input shortcode three_digit majorcode ismajor               major_desc                                      long_desc
1 E11.9      E119         E11       E11   FALSE Type 2 diabetes mellitus Type 2 diabetes mellitus without complications
                                      short_desc validicd9 validicd10
1 Type 2 diabetes mellitus without complications      TRUE       TRUE
```
```
> icd_explain_table(as.icd9("E11.9"))
  input shortcode three_digit majorcode ismajor                                                      major_desc

1 E11.9     E0119        E011      E011   FALSE Activities involving computer technology and electronic devices
                                                            long_desc        short_desc validicd9 validicd10
1 Other activity involving computer technology and electronic devices Computer tech NEC      TRUE       TRUE

> icd_explain_table(as.icd10("E11.9"))
  input shortcode three_digit majorcode ismajor               major_desc                                      long_desc
1 E11.9      E119         E11       E11   FALSE Type 2 diabetes mellitus Type 2 diabetes mellitus without complications
                                      short_desc validicd9 validicd10
1 Type 2 diabetes mellitus without complications      TRUE       TRUE
``` 
Hopefully that's almost a wrap on that.   Took me the most time to get used to travis, werker and dplyr but I think I've figured most of it out.   

One thing I think I could change though is this new function has quite a long function name?  Would love to bounce any ideas, feedback, questions you may have..

**Comment by jackwasey** [comment]
Thanks for all this great work. I've been away for a while, so now catching up. It looks like a great solution. My only reservation is the use of dplyr, which I accept is a useful package, but does mean I'd have to pull in that dependency (and its dependencies, etc.). I'm not in love with the name, but can't think of anything better. Maybe 'icd_explain_as_table'? Will review more thoroughly soon. Thanks again.

**Comment by jackwasey** [comment]
maybe `icd_decode`?

**Comment by edlee123** [comment]
Thank you Jack, no worries, whenever you get round to it, it's probably a bit to review.  It's true it took me little while to figure out how to add dplyr to the package, with non-standard evaluation.   On the plus side the common 'loops' such as left_join (for lookups), filter, are factored into common verbs so helps readability, and hadley has well optimized.    Couple more ideas on names: icd_explain_more, icd_english, icd_details.  I'll keep thinking...

**Comment by jackwasey** [comment]
Another quick look:
'  st_codes9 <- st_codes %>% dplyr::filter(validicd9 == T & validicd10 == F)' looks incorrect, as there are codes that can be valid in either scheme, eg V10 or some such.

Most of your dplyr calls would be syntactically simple to convert to base R. The left join has appeal to people who know SQL, but I'd really prefer using aggregate, which has been doing the same thing, maybe for as long as SQL has existed. Is aggregate aka left join actually needed? I haven't looked in detail, but it strikes me this could be replaced just be generating a list of indices in one expression, to look up values in a vector or data frame. It is often this type of solution which is faster in R then using an optimized sledgehammer!

Also, the pipeline seems clean, and I do like it sometimes, but with many steps, debugging becomes a mess if an error pops up in the middle, and there is a crazy backtrace. I don't know about performance considerations.

**Comment by edlee123** [comment]
Ah that's a good thing for me to explain.  In  icd_explain_table.character where I go:

` st_codes9 <- st_codes %>% dplyr::filter(validicd9 == T & validicd10 == F)
st_codes10 <- st_codes %>% dplyr::filter(validicd10 == T)  # if also a validicd9 will return icd10`

The character could be both valid ICD9 and ICD10, but I default to the ICD10 description. It will show the columns validicd9, validicd10 as both `true`.   

But if the user doesn't want the default behavior on these ambiguous codes, they'd have to cast character to icd9 first.  That's the current set up, but there could be an option as well..

Once I have the st_codesxx, I run icd_explain_table.xxx separately for each, then I use the left_join on line 189-191 to 'lookup' the order of the original input.
`  st_codes %>%
       select(input) %>%
       left_join(y = rbind(out9, out10), by = c("input"))`

There could be spots where steps %>% get numerous, and maybe opportunities to refactor to functions.

**Comment by jackwasey** [comment]
Ed, I've now spent a bit of time reviewing your code, figuring out what you intended, and how to integrate it into `icd`. In short, I made some fairly radical changes. I dropped dplyr and magrittr idioms and recoded using `merge` and `aggregate`. I dropped processing of mixed ICD-9 and ICD-10 which was both complicated, and a rare or absent situation in practice: if the code types really are mixed, the data owner is in a world of trouble, and I don't think there can be a simple, correct result for general use.

Something funny happened to my git branch of your code, so I pushed to a new branch:
https://github.com/jackwasey/icd/tree/explaintable

There isn't much of your original code left, since so much was dplyr, but I preserved the important parts of your implementation. I just realised I'm not sure I addressed your 'brief' flag. Maybe best not to be brief ever, since the function does produce a lot of output in any case. I like simple, so dropping brief and always included the additional columns would be my preference.

The S3 dispatch will take care of some of the logic you used when separating teh default, character and icd-type implementations, so I removed that.

Another reason I don't like dplyr:

```
Attaching package: 'dplyr'
The following objects are masked from 'package:stats':
    filter, lag
The following object is masked from 'package:testthat':
    matches
The following objects are masked from 'package:base':
    intersect, setdiff, setequal, union
```

As an aside, icd9cm_hierarchy should have `major_desc` instead of `major`, and `major` instead of `three_digit`, but right now, I'll leave the status quo. I also need to update naming to make the ICD-9 and ICD-10 lookup table names consistent.

I know you invested some time in `dplyr`, but IMO this is best suited to data projects not to packages used by thousands of people. 

Let me know what you think.

The next step is to add more tests to cover all the flags the functions offer and more corner cases with NAs, invalid data, etc. Given I don't want to have mixed ICD-9 and ICD-10, having the valid_icd9 and valid_icd10 flags is a bit discrepant, and could be simplified to `valid` according to whether the user states, or we guess, the ICD code type.

**Comment by edlee123** [comment]
Hi Jack, 

I quite liked the factorings and simplification.. Simplicity is the essence of good design I think.  Well I do agree the R base functions will be more stable and easier to manage in the end.  Anyways, performance doesn't seem so much an issue as there aren't a huge # of unique explanations.  

For the 'brief' option, I don't think it's essential, that was more for my viewing convenience when I want to see many rows at a time in the console.  But the user could select the columns they want outside the function too.    One personal preference for reading odd codes like '362.5', I did like reading 'major' description before 'short_desc' column.  Another nice to have is decimal code next to short-code for reference purpose.

I agree the issue of mixed codes can be done better e.g. issue #96, if you try:
`icd_explain_table(c('E11.9', 'I10'))`

There it's hard to make out what happened in the first row..  A couple options, perhaps add warning + documentation, or only allow explicit icd9 or icd10 as opposed to character vector.  

I think icd_explain_table resolves Issue #95 though.  I'll see what other tests we might add.

**Pull request merged**
